// built by nnnsightnnn — signal from noise
// The 32 teams: madden.tools abbreviation -> display name, catalog slug, colors.
export const TEAMS = {
  ARI: { name: 'Arizona Cardinals', slug: 'cardinals', color: '#97233F', div: 'NFC West' },
  ATL: { name: 'Atlanta Falcons', slug: 'falcons', color: '#A71930', div: 'NFC South' },
  BAL: { name: 'Baltimore Ravens', slug: 'ravens', color: '#241773', div: 'AFC North' },
  BUF: { name: 'Buffalo Bills', slug: 'bills', color: '#00338D', div: 'AFC East' },
  CAR: { name: 'Carolina Panthers', slug: 'panthers', color: '#0085CA', div: 'NFC South' },
  CHI: { name: 'Chicago Bears', slug: 'bears', color: '#0B162A', div: 'NFC North' },
  CIN: { name: 'Cincinnati Bengals', slug: 'bengals', color: '#FB4F14', div: 'AFC North' },
  CLE: { name: 'Cleveland Browns', slug: 'browns', color: '#311D00', div: 'AFC North' },
  DAL: { name: 'Dallas Cowboys', slug: 'cowboys', color: '#003594', div: 'NFC East' },
  DEN: { name: 'Denver Broncos', slug: 'broncos', color: '#FB4F14', div: 'AFC West' },
  DET: { name: 'Detroit Lions', slug: 'lions', color: '#0076B6', div: 'NFC North' },
  GB: { name: 'Green Bay Packers', slug: 'packers', color: '#203731', div: 'NFC North' },
  HOU: { name: 'Houston Texans', slug: 'texans', color: '#03202F', div: 'AFC South' },
  IND: { name: 'Indianapolis Colts', slug: 'colts', color: '#002C5F', div: 'AFC South' },
  JAX: { name: 'Jacksonville Jaguars', slug: 'jaguars', color: '#006778', div: 'AFC South' },
  KC: { name: 'Kansas City Chiefs', slug: 'chiefs', color: '#E31837', div: 'AFC West' },
  LV: { name: 'Las Vegas Raiders', slug: 'raiders', color: '#000000', div: 'AFC West' },
  LAC: { name: 'Los Angeles Chargers', slug: 'chargers', color: '#0080C6', div: 'AFC West' },
  LAR: { name: 'Los Angeles Rams', slug: 'rams', color: '#003594', div: 'NFC West' },
  MIA: { name: 'Miami Dolphins', slug: 'dolphins', color: '#008E97', div: 'AFC East' },
  MIN: { name: 'Minnesota Vikings', slug: 'vikings', color: '#4F2683', div: 'NFC North' },
  NE: { name: 'New England Patriots', slug: 'patriots', color: '#002244', div: 'AFC East' },
  NO: { name: 'New Orleans Saints', slug: 'saints', color: '#D3BC8D', div: 'NFC South' },
  NYG: { name: 'New York Giants', slug: 'giants', color: '#0B2265', div: 'NFC East' },
  NYJ: { name: 'New York Jets', slug: 'jets', color: '#125740', div: 'AFC East' },
  PHI: { name: 'Philadelphia Eagles', slug: 'eagles', color: '#004C54', div: 'NFC East' },
  PIT: { name: 'Pittsburgh Steelers', slug: 'steelers', color: '#FFB612', div: 'AFC North' },
  SF: { name: 'San Francisco 49ers', slug: '49ers', color: '#AA0000', div: 'NFC West' },
  SEA: { name: 'Seattle Seahawks', slug: 'seahawks', color: '#002244', div: 'NFC West' },
  TB: { name: 'Tampa Bay Buccaneers', slug: 'buccaneers', color: '#D50A0A', div: 'NFC South' },
  TEN: { name: 'Tennessee Titans', slug: 'titans', color: '#4B92DB', div: 'AFC South' },
  WAS: { name: 'Washington Commanders', slug: 'commanders', color: '#5A1414', div: 'NFC East' },
};
